### ISSUE TITLE
Exercises 00 - #4: `manual_seed` called only once?

### ISSUE THREAD

**Issue by fdegrave** [mrdbourke/pytorch-deep-learning#245]
In [this section](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/00_pytorch_fundamentals_exercise_solutions.ipynb) it says that we have to reset the seed every time a new `rand()` is called. However it is not the case in the [solution of exercise 4](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/00_pytorch_fundamentals_exercise_solutions.ipynb). How come? Is it correct?

**Comment by PawKanarek** [comment]
I was baffled about this also. In the video i had impression like that was important to use `manual_seed` everytime. 

But in reality setting it every time is pointless, because we would get everytime the same tensor when calling torch.rand: 
![image](https://user-images.githubusercontent.com/15096514/210632772-b54f9030-61f8-4d9c-98d1-2df005fbba5a.png)

But when we do it only once, we stil have reproducible results. but every new tensor is different :) 
![image](https://user-images.githubusercontent.com/15096514/210632851-56290a4c-ea2b-448b-834e-8aef62018d43.png)

**Comment by fdegrave** [comment]
Ok thanks! Not clear indeed in the doc...
