### ISSUE TITLE
Hugging Face FoodVision Mini Demo is not running!

### ISSUE THREAD

**Issue by Alejandro-Casanova** [mrdbourke/pytorch-deep-learning#664]
[https://huggingface.co/spaces/mrdbourke/foodvision_mini](https://huggingface.co/spaces/mrdbourke/foodvision_mini)

**Comment by mrdbourke** [comment]
hmmm 🤔 , thank you for the heads up!

going to try a factory reboot, will check in here soon.

looks like foodvision_big is broken too :O - https://huggingface.co/spaces/mrdbourke/foodvision_big

<img width="1347" alt="Screenshot 2023-10-05 at 4 50 17 pm" src="https://github.com/mrdbourke/pytorch-deep-learning/assets/16750345/dec44b76-560c-447b-9b55-9a32bfa6ae45">

**Comment by mrdbourke** [comment]
Fixed this, turns out the cached versions of the apps expire overtime.

Also, I think Gradio version 3.1.4 may have been outdated (as of writing, October 13th 2023, Gradio 3.14.0 is out).

I tried the "Restart Space" and "Factory Reboot" options but these did not seem to work.

<img width="1453" alt="Screenshot 2023-10-13 at 2 16 27 pm" src="https://github.com/mrdbourke/pytorch-deep-learning/assets/16750345/781270d5-bfa5-43ab-a978-6ab4f99b96cd">

What did work though was making a new commit to the Space (the Space gets rebuilt with every new commit).

I changed the `requirements.txt` file in some of the Spaces to:

```
torch
torchvision
gradio==3.14.0
```

And this seems to work.

However, another Space works just fine (after a new commit) by just using:

```
torch==1.12.0
torchvision==0.13.0
gradio==3.1.4
```

Which is the same as the original.

## Summary

To fix, try making a new commit to the Space to get it to manually rebuild itself.

Also, Spaces seem to time out after ~30 days of inactivity so they may need a manually rebuild (e.g. by making a new commit) afterwards.

See the working demos here: https://huggingface.co/spaces/mrdbourke/foodvision_mini

<img width="1249" alt="Screenshot 2023-10-13 at 2 22 54 pm" src="https://github.com/mrdbourke/pytorch-deep-learning/assets/16750345/78a27208-cfed-4e9f-a083-9a11eb758ac0">
