### ISSUE TITLE
About the poor performance of the custom ViT.

### ISSUE THREAD

**Issue by toxfu** [mrdbourke/pytorch-deep-learning#670]
In the paper's replication of the ViT model, you mentioned that it was necessary to establish the correct order of `position_embedding` when flattening the image so that the network learns the correct sequence in which it was done. However, when you create the ViT class, you assign random values like this:

```python
self.position_embedding = nn.Parameter(data=torch.randn(1, self.num_patches+1, embedding_dim),  requires_grad=True)
```

And I find in Attention Is All You Need

3.5 Positional Encoding
Since our model contains no recurrence and no convolution, in order for the model to make use of the order of the sequence, we must inject some information about the relative or absolute position of the tokens in the sequence. To this end, we add "positional encodings" to the input embeddings at the bottoms of the encoder and decoder stacks. The positional encodings have the same dimension $d_{\text {model }}$ as the embeddings, so that the two can be summed. There are many choices of positional encodings, learned and fixed [9].
In this work, we use sine and cosine functions of different frequencies:
`
P E(pos,2i) = sin(pos/100002i/dmodel)
P E(pos,2i+1) = cos(pos/100002i/dmodel)
`
Could this be the primary reason for the poor performance, beyond the quantity of data?

**Comment by mrdbourke** [comment]
Hi @toxfu , 

Yes, you're right, that could be one reason our ViT isn't performing as well.

However, the embeddings in Attention Is All You Need and the Vision Transformer paper are slightly different.

In the ViT paper, the authors said they found that learned (e.g. our positional embeddings) and fixed (e.g. sine and cosine functions) perform similarly.

<img width="818" alt="Screenshot 2023-10-13 at 2 50 57 pm" src="https://github.com/mrdbourke/pytorch-deep-learning/assets/16750345/9c50e4f5-6483-4b8c-9737-fe5d208764ab">

See Appendix D.4 in https://arxiv.org/abs/2010.11929

I chose to use the learned embeddings (1-D Pos Embed) in the course due to simplicity.

However, a good experiment would be to try sine and cosine with our setup and see if that makes a difference.
